// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "HealthCheck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health-check"
                ],
                "summary": "HealthCheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.JsonResponse-bool"
                        }
                    }
                }
            }
        },
        "/v1/space-craft": {
            "get": {
                "description": "FetchSpaceCraft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "space-craft"
                ],
                "summary": "FetchSpaceCraft",
                "parameters": [
                    {
                        "type": "string",
                        "description": "space-craft name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "space-craft status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "space-craft class",
                        "name": "class",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.JsonResponse-bool"
                        }
                    }
                }
            },
            "post": {
                "description": "CreateSpaceCraft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "space-craft"
                ],
                "summary": "CreateSpaceCraft",
                "parameters": [
                    {
                        "description": "Create payload",
                        "name": "space-craft",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SpaceShipCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.JsonResponse-bool"
                        }
                    }
                }
            }
        },
        "/v1/space-craft/{id}": {
            "get": {
                "description": "GetSpaceCraft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "space-craft"
                ],
                "summary": "GetSpaceCraft",
                "parameters": [
                    {
                        "type": "string",
                        "description": "space-craft id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.JsonResponse-response_SpaceCraftResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "EditSpaceCraft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "space-craft"
                ],
                "summary": "EditSpaceCraft",
                "parameters": [
                    {
                        "type": "string",
                        "description": "space-craft id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Edit payload",
                        "name": "space-craft",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SpaceShipEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.JsonResponse-bool"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteSpaceCraft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "space-craft"
                ],
                "summary": "DeleteSpaceCraft",
                "parameters": [
                    {
                        "type": "string",
                        "description": "space-craft id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.JsonResponse-bool"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ErrorResponse": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "integer"
                },
                "error_message": {
                    "type": "string"
                }
            }
        },
        "controller.JsonResponse-bool": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "boolean"
                },
                "error": {
                    "$ref": "#/definitions/controller.ErrorResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "controller.JsonResponse-response_SpaceCraftResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/response.SpaceCraftResponse"
                },
                "error": {
                    "$ref": "#/definitions/controller.ErrorResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "request.SpaceShipArmament": {
            "type": "object",
            "properties": {
                "armament_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "request.SpaceShipCreateRequest": {
            "type": "object",
            "properties": {
                "armaments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.SpaceShipArmament"
                    }
                },
                "class": {
                    "type": "string"
                },
                "crew": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "request.SpaceShipEditRequest": {
            "type": "object",
            "properties": {
                "class": {
                    "type": "string"
                },
                "crew": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "response.SpaceCraftArmamentResponse": {
            "type": "object",
            "properties": {
                "qty": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.SpaceCraftResponse": {
            "type": "object",
            "properties": {
                "armament": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.SpaceCraftArmamentResponse"
                    }
                },
                "class": {
                    "type": "string"
                },
                "crew": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "valued": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Imperial Fleet Inventory",
	Description:      "Imperial Fleet Inventory Management System Service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
